version: '2.1'
services:
  browser:
    restart: always
    build: "./balena-wpe"
    privileged: true
    network_mode: host
    environment:
      WPE_URL: http://localhost:90
    depends_on:
      - magicmirror
    # Don't use healthcheck, it won't work for some reason: https://github.com/balena-io-projects/balena-wpe/issues/51
    command: >
      /bin/bash -c "
        while ! wget -O /dev/null $WPE_URL > /dev/null;
        do
          echo 'Waiting for MagicMirror to be ready...';
          sleep 10;
          exit 1;
        done;
        echo 'MagicMirror up, starting the Browser now!';
        /wpe-init
      "
    #healthcheck:
     # test: ["CMD", "wget", "-q", "-O", "/dev/null", "$WPE_URL"]
  magicmirror:
    restart: always
    build: ./MagicMirror
    privileged: true
    network_mode: host